# Generated by Django 2.1.7 on 2026-02-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupplyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='all_objects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='lime_image_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='path_objects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='safety_explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
