# Generated by Django 2.1.7 on 2026-02-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupplyApp', '0002_auto_20260205_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='all_objects',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='lime_image_path',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='path_objects',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='safety_explanation',
        ),
        migrations.AddField(
            model_name='mission',
            name='ranked_personnel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
